//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfLocalizationResx.LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationInfoRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationInfoRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfLocalizationResx.LocalResources.LocalizationInfoRes", typeof(LocalizationInfoRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string btnExit_Content {
            get {
                return ResourceManager.GetString("btnExit.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to left.
        /// </summary>
        public static string chkRightToLeft_Content {
            get {
                return ResourceManager.GetString("chkRightToLeft.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (en-US).
        /// </summary>
        public static string cmbLanguageItem1 {
            get {
                return ResourceManager.GetString("cmbLanguageItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (de-DE).
        /// </summary>
        public static string cmbLanguageItem2 {
            get {
                return ResourceManager.GetString("cmbLanguageItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew (he-IL).
        /// </summary>
        public static string cmbLanguageItem3 {
            get {
                return ResourceManager.GetString("cmbLanguageItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CountryFlag {
            get {
                object obj = ResourceManager.GetObject("CountryFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale Information.
        /// </summary>
        public static string gbLocaleInformation_Header {
            get {
                return ResourceManager.GetString("gbLocaleInformation.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Display Input.
        /// </summary>
        public static string gbValueInput_Header {
            get {
                return ResourceManager.GetString("gbValueInput.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound Values.
        /// </summary>
        public static string grpBoundValues_Header {
            get {
                return ResourceManager.GetString("grpBoundValues.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached Property (Content/Tooltip):.
        /// </summary>
        public static string lblAttachedLabel_Content {
            get {
                return ResourceManager.GetString("lblAttachedLabel.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World (Res).
        /// </summary>
        public static string lblAttachedValue_Content {
            get {
                return ResourceManager.GetString("lblAttachedValue.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string lblAttachedValue_Margin {
            get {
                return ResourceManager.GetString("lblAttachedValue.Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World Tooltip.
        /// </summary>
        public static string lblAttachedValue_Tooltip {
            get {
                return ResourceManager.GetString("lblAttachedValue.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a date value:.
        /// </summary>
        public static string lblDateLabel_Content {
            get {
                return ResourceManager.GetString("lblDateLabel.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow Direction:.
        /// </summary>
        public static string lblFlowDirectionName_Content {
            get {
                return ResourceManager.GetString("lblFlowDirectionName.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language:.
        /// </summary>
        public static string lblLanguageSelections_Content {
            get {
                return ResourceManager.GetString("lblLanguageSelections.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time:.
        /// </summary>
        public static string lblLocalDateTimeName_Content {
            get {
                return ResourceManager.GetString("lblLocalDateTimeName.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale:.
        /// </summary>
        public static string lblLocale_Content {
            get {
                return ResourceManager.GetString("lblLocale.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayName:.
        /// </summary>
        public static string lblLocaleName_Content {
            get {
                return ResourceManager.GetString("lblLocaleName.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric:.
        /// </summary>
        public static string lblLocaleNumberName_Content {
            get {
                return ResourceManager.GetString("lblLocaleNumberName.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Name:.
        /// </summary>
        public static string lblNativeName_Content {
            get {
                return ResourceManager.GetString("lblNativeName.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a numeric value:.
        /// </summary>
        public static string lblNumberLabel_Content {
            get {
                return ResourceManager.GetString("lblNumberLabel.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World Markup Extension Default:.
        /// </summary>
        public static string lblResxHelloWorldMarkupExtension1Label_Content {
            get {
                return ResourceManager.GetString("lblResxHelloWorldMarkupExtension1Label.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Markup Extensions Explicit:.
        /// </summary>
        public static string lblResxHelloWorldMarkupExtension2Label_Content {
            get {
                return ResourceManager.GetString("lblResxHelloWorldMarkupExtension2Label.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World Strong Type:.
        /// </summary>
        public static string lblResxHelloWorldStrongLabel_Content {
            get {
                return ResourceManager.GetString("lblResxHelloWorldStrongLabel.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Theme:.
        /// </summary>
        public static string lblThemeSelection_Content {
            get {
                return ResourceManager.GetString("lblThemeSelection.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string mnuExit_Header {
            get {
                return ResourceManager.GetString("mnuExit.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string mnuFile_Header {
            get {
                return ResourceManager.GetString("mnuFile.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string mnuHelp_Header {
            get {
                return ResourceManager.GetString("mnuHelp.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string mnuHelpAbout_Header {
            get {
                return ResourceManager.GetString("mnuHelpAbout.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Content.
        /// </summary>
        public static string mnuHelpContent_Header {
            get {
                return ResourceManager.GetString("mnuHelpContent.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string mnuSave_Header {
            get {
                return ResourceManager.GetString("mnuSave.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye (Res).
        /// </summary>
        public static string MyContext_GoodBye_Header {
            get {
                return ResourceManager.GetString("MyContext_GoodBye.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Context (Res).
        /// </summary>
        public static string MyContext_Hello_Header {
            get {
                return ResourceManager.GetString("MyContext_Hello.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Info.
        /// </summary>
        public static string wndLocalizationInfo_Title {
            get {
                return ResourceManager.GetString("wndLocalizationInfo.Title", resourceCulture);
            }
        }
    }
}
