//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfLocalizationResx.LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StartForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StartForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfLocalizationResx.LocalResources.StartForm", typeof(StartForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string btnExit_Content {
            get {
                return ResourceManager.GetString("btnExit.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Information.
        /// </summary>
        public static string btnLocalizationInfo_Content {
            get {
                return ResourceManager.GetString("btnLocalizationInfo.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Info (Attached Property).
        /// </summary>
        public static string btnLocalizationInfoAttached_Content {
            get {
                return ResourceManager.GetString("btnLocalizationInfoAttached.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CountryFlag {
            get {
                object obj = ResourceManager.GetObject("CountryFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpf Resx Localization Samples.
        /// </summary>
        public static string frmStartMenuForm_Title {
            get {
                return ResourceManager.GetString("frmStartMenuForm.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string gbSamples_Header {
            get {
                return ResourceManager.GetString("gbSamples.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample is localized in English and German using Resx Resources.
        /// </summary>
        public static string txtSubHeader_Text {
            get {
                return ResourceManager.GetString("txtSubHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resx Resource Localization Example.
        /// </summary>
        public static string WindowHeader_Text {
            get {
                return ResourceManager.GetString("WindowHeader.Text", resourceCulture);
            }
        }
    }
}
